name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout
      - run: npm install
      - run: npm run prettier:check
      - run: npm run test
